/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: 'tw-',
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
    './assets/css/**/*.scss',
    './assets/css/**/*.css',
  ],
  theme: {
    extend: {
      colors: {
        'base-bg': '#07080b',
        'surface-1': '#0e1117',
        'surface-2': '#151922',
        'surface-3': '#1e2430',
        'surface-4': '#283040',
        'primary-amber': '#e5a93c',
        'primary-hover': '#f5b748',
        'primary-active': '#d49528',
        'accent-cyan': '#38bdf8',
        'accent-red': '#f43f5e',
        'accent-green': '#10b981',
        'text-primary': '#f8fafc',
        'text-secondary': '#cbd5e1',
        'text-muted': '#94a3b8',
        'text-subtle': '#64748b',
        'border-subtle': 'rgba(255, 255, 255, 0.07)',
        'border-medium': 'rgba(255, 255, 255, 0.14)',
        'border-strong': 'rgba(255, 255, 255, 0.24)',
        'border-focus': 'rgba(229, 169, 60, 0.55)',
      },
      screens: {
        xs: '480px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      boxShadow: {
        glow: '0 0 28px rgba(229, 169, 60, 0.22)',
        poster: '0 12px 30px rgba(0, 0, 0, 0.65), 0 2px 8px rgba(0, 0, 0, 0.4)',
        'cinema-sm': '0 4px 12px rgba(0, 0, 0, 0.4)',
        'cinema-md': '0 8px 24px rgba(0, 0, 0, 0.55)',
        'cinema-lg': '0 16px 40px rgba(0, 0, 0, 0.7)',
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        display: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'sans-serif',
        ],
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};
